inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'pkg/**/*'

Style/HashSyntax:
  Enabled: false

# dealbreaker:
Style/TrailingCommaInLiteral:
  Enabled: false
