---
sudo: false
language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
script: 'bundle exec rake test'
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.0
