---
default:
  .travis.yml:
    rvms:
      - 1.8.7
      - 1.9.3
      - 2.0.0
    excludes:
      - rvm: 1.9.3
        env: PUPPET_GEM_VERSION="~> 2.7.0"
      - rvm: 2.0.0
        env: PUPPET_GEM_VERSION="~> 2.7.0"
    puppets:
      - 2.7.0
      - 3.3.0
      - 3.4.0

puppetlabs-mysql:
  .travis.yml:
    rvms:
      - 1.8.7
      - 1.9.3
    puppets:
      - 2.7.0
      - 3.4.0
puppetlabs-apache:
