---
.travis.yml:
  script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
  rvms:
    - 1.8.7
    - 1.9.3
    - 2.0.0
  excludes:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.7.0"
  puppets:
    - 2.7.0
    - 3.3.0
    - 3.4.0
Gemfile:
  gems:
    - name: rake
      version: 10.1.1
    - name: rspec-puppet
      version: '>=1.0.0'
    - name: puppetlabs_spec_helper
    - name: serverspec
    - name: puppet-lint
    - name: beaker
    - name: beaker-rspec
    - name: rspec
      version: '~> 2.11'
LICENSE:
  copyrights:
    - year: 2012
      owner: Puppet Labs Inc
